### ISSUE TITLE
First text entered in Logs dialog has "IMPROV" prefixed

### ISSUE THREAD

**Issue by TD-er** [esphome/esp-web-tools#110]
![image](https://user-images.githubusercontent.com/3751318/141288687-95e3f8e9-4118-41f6-b2d0-36289baab10c.png)

I entered `wifidisconnect`, which is a known command in ESPEasy.
But as you can see, the first entered command is always prefixed with `IMPROV`.

```
> wifidisconnect
>IMPROVwifidisconnect
334090 : Info   : Command unknown: IMPROVwifidisconnect
Command unknown: IMPROVwifidisconnect
```

(this was also a test to confirm copy/paste now works :) )

**Comment by balloob** [comment]
I think the issue happens here as we don’t finish the IMPROV packets with a new line, and since your firmware doesn’t support IMPROV, it considers it input to be received.

https://github.com/improv-wifi/sdk-serial-js/blob/main/src/serial.ts#L153

I will update Improv to make sure all packets end with a new line.
